version: "3.7"

services:
  app:
    image: learning-docker/node:v1
    build:
      context: .
      dockerfile: dockerfile
    container_name: apptest
    restart: unless-stopped
    environment:
      - DB_URI=${DB_URI}
      - DB_NAME=${DB_NAME}
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - db
    networks:
      - db-network
      - redis-network
  db:
    image: mongo
    container_name: dbtest
    restart: unless-stopped
    ports: [ "27020-27022:27017-27019" ]
    hostname: db
    volumes:
      - .docker/data/db:/data/db
    networks:
      - db-network
  
  redis:
    image: redis:5-alpine
    container_name: redistest
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped
    networks:
      - redis-network

#Docker Networks
networks:
  db-network:
    name: db_network
    driver: bridge
  redis-network:
    name: redis_network
    driver: bridge